#!/usr/bin/env python3
"""Generate dicore_text_digest_gen.h — the INTEL_0059 build-time .text digest.

Hashes the FILE BYTES [p_offset, p_offset + p_filesz) of the first PF_X
PT_LOAD segment of a linked libdicore.so. The runtime probe
(deviceintelligence/src/main/cpp/dicore/detectors/native_integrity/text_digest_probe.cpp)
hashes the same logical byte range at runtime — [dlpi_addr + p_vaddr,
+ p_filesz) via dl_iterate_phdr — so the two digests are byte-equal on an
untampered build.

Why segment file-bytes and not the whole .so: the generated digest array is
compiled into the library, so any range containing it (whole file, .rodata)
could never converge — the digest would change the bytes it digests. The
executable segment contains no generated data (the array lands in .rodata, a
non-exec PT_LOAD), so the digest is a fixed point: embedding it does not
change it.

Convergence: a header can only be generated after the .so is linked, but the
probe TU must include it to compile. CMake therefore seeds the header with an
all-zero "no baseline" digest at configure time (the probe skips verification
against it — fail-open, never a zeroed-baseline compare) and this tool runs
POST_BUILD. A clean build ships the zero seed; the NEXT incremental build
recompiles the probe with the real digest and stays stable from then on (this
tool rewrites the header only when the digest changed, so timestamps settle).

    python3 tools/native/gen-dicore-text-digest.py <libdicore.so> <out.header> [elf-cap]

<elf-cap> (bytes, default 512 MiB) bounds the input size as a sanity guard.
"""
import hashlib
import os
import struct
import sys

PT_LOAD = 1
PF_X = 1


def exec_segment(path, cap):
    """(sha256-hex, p_offset, p_filesz) of the first PF_X PT_LOAD segment."""
    size = os.path.getsize(path)
    if size > cap:
        raise SystemExit(f"{path}: {size} bytes exceeds cap {cap} — refusing")
    with open(path, "rb") as f:
        data = f.read()
    if len(data) < 64 or data[:4] != b"\x7fELF":
        raise SystemExit(f"{path}: not an ELF file")
    is64 = data[4] == 2
    end = "<" if data[5] == 1 else ">"
    if is64:
        e_phoff = struct.unpack_from(end + "Q", data, 0x20)[0]
        e_phentsize = struct.unpack_from(end + "H", data, 0x36)[0]
        e_phnum = struct.unpack_from(end + "H", data, 0x38)[0]
        off_off, sz_off, fl_off = 8, 32, 4       # Elf64_Phdr field offsets
        fmt_addr = end + "Q"
    else:
        e_phoff = struct.unpack_from(end + "I", data, 0x1C)[0]
        e_phentsize = struct.unpack_from(end + "H", data, 0x2A)[0]
        e_phnum = struct.unpack_from(end + "H", data, 0x2C)[0]
        off_off, sz_off, fl_off = 4, 16, 24      # Elf32_Phdr field offsets
        fmt_addr = end + "I"
    for i in range(e_phnum):
        ph = e_phoff + i * e_phentsize
        if struct.unpack_from(end + "I", data, ph)[0] != PT_LOAD:
            continue
        if not struct.unpack_from(end + "I", data, ph + fl_off)[0] & PF_X:
            continue
        p_offset = struct.unpack_from(fmt_addr, data, ph + off_off)[0]
        p_filesz = struct.unpack_from(fmt_addr, data, ph + sz_off)[0]
        seg = data[p_offset:p_offset + p_filesz]
        if len(seg) != p_filesz:
            raise SystemExit(f"{path}: truncated exec segment "
                             f"(offset={p_offset} size={p_filesz} file={len(data)})")
        return hashlib.sha256(seg).hexdigest(), p_offset, p_filesz
    raise SystemExit(f"{path}: no PF_X PT_LOAD segment")


def render(digest_hex, so_name, p_offset, p_filesz):
    body = ", ".join(f"0x{digest_hex[i:i + 2]}" for i in range(0, 64, 2))
    return f"""#pragma once
// AUTO-GENERATED by tools/native/gen-dicore-text-digest.py — do not edit.
// SHA-256 of libdicore.so's executable PT_LOAD segment FILE BYTES
// (source: {so_name}, offset={p_offset}, size={p_filesz}). The runtime probe
// (text_digest_probe.cpp, INTEL_0059) hashes the same byte range at
// [dlpi_addr + p_vaddr, + p_filesz) — keep both sides in lock-step.
//
// All-zero means NO BASELINE: a clean build seeds this header before the .so
// exists and regenerates it after the link, so the real digest lands on the
// next incremental build. The probe treats all-zero as "skip verification"
// (fail-open) — never as an expected value.
#include <stdint.h>
static const uint8_t DICORE_TEXT_DIGEST[32] = {{ {body} }};
"""


def main():
    if len(sys.argv) < 3 or len(sys.argv) > 4:
        raise SystemExit(__doc__)
    so, out = sys.argv[1], sys.argv[2]
    cap = int(sys.argv[3]) if len(sys.argv) == 4 else 512 * 1024 * 1024
    digest_hex, p_offset, p_filesz = exec_segment(so, cap)
    new = render(digest_hex, os.path.basename(so), p_offset, p_filesz)
    if os.path.exists(out):
        with open(out) as f:
            if f.read() == new:
                print(f"dicore text digest: unchanged ({digest_hex[:16]}…)")
                return
    with open(out, "w") as f:
        f.write(new)
    print(f"dicore text digest: wrote {out} ({digest_hex[:16]}…)")


if __name__ == "__main__":
    main()
