// GENERATED by tools/registry/gen-signal-catalogue.py — do not edit.
//
// TESTBED ONLY (worst-case narrative 2026-09-10, R8): this catalogue and its
// resources bake the FULL detector prose into the app. Fine for this lab app;
// a PRODUCTION app must NOT copy it — that ships the evasion cookbook in
// plaintext to every attacker. Production renders prose server-side.
package tech.thessemaj.deviceintelligence.sample.signal

import androidx.annotation.StringRes
import tech.thessemaj.deviceintelligence.sample.R

/** The families the signal catalogue is organised into. */
enum class SignalGroup(@StringRes val title: Int, @StringRes val blurb: Int) {
    Attestation(R.string.signal_group_attestation, R.string.signal_group_attestation_blurb),
    RuntimeInstrumentation(R.string.signal_group_runtimeinstrumentation, R.string.signal_group_runtimeinstrumentation_blurb),
    AntiAnalysis(R.string.signal_group_antianalysis, R.string.signal_group_antianalysis_blurb),
    RootAndSystem(R.string.signal_group_rootandsystem, R.string.signal_group_rootandsystem_blurb),
    PackageIntegrity(R.string.signal_group_packageintegrity, R.string.signal_group_packageintegrity_blurb),
    VirtualEnvironments(R.string.signal_group_virtualenvironments, R.string.signal_group_virtualenvironments_blurb),
}

/**
 * Every signal code the SDK can emit, paired with what it means.
 *
 * The wire carries only the opaque code; `:verifier` resolves the detector, kind,
 * severity and title from the registry. What it does NOT carry is the explanation —
 * the meaning of the finding and the capability it implies — so that lives here,
 * generated from the same registry.
 *
 * [reach] is null for codes the docs have not described yet.
 */
enum class SignalCatalogue(
    val group: SignalGroup,
    @StringRes val meaning: Int,
    @StringRes val reach: Int?,
    /** A retired code should never arrive. If one does, the registry is out of date. */
    val retired: Boolean = false,
) {
    INTEL_0000(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0000_meaning,
        reach = R.string.intel_0000_reach,
    ),
    INTEL_0001(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0001_meaning,
        reach = R.string.intel_0001_reach,
    ),
    INTEL_0002(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0002_meaning,
        reach = R.string.intel_0002_reach,
    ),
    INTEL_0003(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0003_meaning,
        reach = R.string.intel_0003_reach,
    ),
    INTEL_0004(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0004_meaning,
        reach = R.string.intel_0004_reach,
    ),
    INTEL_0005(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0005_meaning,
        reach = R.string.intel_0005_reach,
    ),
    INTEL_0006(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0006_meaning,
        reach = R.string.intel_0006_reach,
    ),
    INTEL_0007(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0007_meaning,
        reach = R.string.intel_0007_reach,
    ),
    INTEL_0008(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0008_meaning,
        reach = R.string.intel_0008_reach,
    ),
    INTEL_0009(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0009_meaning,
        reach = R.string.intel_0009_reach,
    ),
    INTEL_0010(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0010_meaning,
        reach = R.string.intel_0010_reach,
    ),
    INTEL_0011(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0011_meaning,
        reach = null,
        retired = true,
    ),
    INTEL_0012(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0012_meaning,
        reach = R.string.intel_0012_reach,
    ),
    INTEL_0013(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0013_meaning,
        reach = R.string.intel_0013_reach,
    ),
    INTEL_0014(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0014_meaning,
        reach = R.string.intel_0014_reach,
    ),
    INTEL_0015(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0015_meaning,
        reach = R.string.intel_0015_reach,
    ),
    INTEL_0016(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0016_meaning,
        reach = R.string.intel_0016_reach,
    ),
    INTEL_0017(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0017_meaning,
        reach = R.string.intel_0017_reach,
    ),
    INTEL_0018(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0018_meaning,
        reach = R.string.intel_0018_reach,
    ),
    INTEL_0019(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0019_meaning,
        reach = R.string.intel_0019_reach,
    ),
    INTEL_0020(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0020_meaning,
        reach = null,
        retired = true,
    ),
    INTEL_0021(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0021_meaning,
        reach = R.string.intel_0021_reach,
    ),
    INTEL_0022(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0022_meaning,
        reach = R.string.intel_0022_reach,
    ),
    INTEL_0023(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0023_meaning,
        reach = R.string.intel_0023_reach,
    ),
    INTEL_0024(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0024_meaning,
        reach = R.string.intel_0024_reach,
    ),
    INTEL_0025(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0025_meaning,
        reach = R.string.intel_0025_reach,
    ),
    INTEL_0026(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0026_meaning,
        reach = R.string.intel_0026_reach,
    ),
    INTEL_0027(
        group = SignalGroup.VirtualEnvironments,
        meaning = R.string.intel_0027_meaning,
        reach = R.string.intel_0027_reach,
    ),
    INTEL_0028(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0028_meaning,
        reach = R.string.intel_0028_reach,
    ),
    INTEL_0029(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0029_meaning,
        reach = R.string.intel_0029_reach,
    ),
    INTEL_0030(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0030_meaning,
        reach = R.string.intel_0030_reach,
    ),
    INTEL_0031(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0031_meaning,
        reach = R.string.intel_0031_reach,
    ),
    INTEL_0032(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0032_meaning,
        reach = R.string.intel_0032_reach,
    ),
    INTEL_0033(
        group = SignalGroup.VirtualEnvironments,
        meaning = R.string.intel_0033_meaning,
        reach = R.string.intel_0033_reach,
    ),
    INTEL_0034(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0034_meaning,
        reach = R.string.intel_0034_reach,
    ),
    INTEL_0035(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0035_meaning,
        reach = R.string.intel_0035_reach,
    ),
    INTEL_0036(
        group = SignalGroup.AntiAnalysis,
        meaning = R.string.intel_0036_meaning,
        reach = R.string.intel_0036_reach,
    ),
    INTEL_0037(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0037_meaning,
        reach = R.string.intel_0037_reach,
    ),
    INTEL_0038(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0038_meaning,
        reach = R.string.intel_0038_reach,
    ),
    INTEL_0039(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0039_meaning,
        reach = null,
        retired = true,
    ),
    INTEL_0040(
        group = SignalGroup.AntiAnalysis,
        meaning = R.string.intel_0040_meaning,
        reach = R.string.intel_0040_reach,
    ),
    INTEL_0041(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0041_meaning,
        reach = R.string.intel_0041_reach,
    ),
    INTEL_0042(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0042_meaning,
        reach = R.string.intel_0042_reach,
    ),
    INTEL_0043(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0043_meaning,
        reach = R.string.intel_0043_reach,
    ),
    INTEL_0044(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0044_meaning,
        reach = R.string.intel_0044_reach,
    ),
    INTEL_0045(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0045_meaning,
        reach = R.string.intel_0045_reach,
    ),
    INTEL_0046(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0046_meaning,
        reach = R.string.intel_0046_reach,
    ),
    INTEL_0047(
        group = SignalGroup.VirtualEnvironments,
        meaning = R.string.intel_0047_meaning,
        reach = R.string.intel_0047_reach,
    ),
    INTEL_0048(
        group = SignalGroup.VirtualEnvironments,
        meaning = R.string.intel_0048_meaning,
        reach = R.string.intel_0048_reach,
    ),
    INTEL_0049(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0049_meaning,
        reach = R.string.intel_0049_reach,
    ),
    INTEL_0050(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0050_meaning,
        reach = R.string.intel_0050_reach,
    ),
    INTEL_0051(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0051_meaning,
        reach = R.string.intel_0051_reach,
    ),
    INTEL_0052(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0052_meaning,
        reach = R.string.intel_0052_reach,
    ),
    INTEL_0053(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0053_meaning,
        reach = R.string.intel_0053_reach,
    ),
    INTEL_0054(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0054_meaning,
        reach = R.string.intel_0054_reach,
    ),
    INTEL_0055(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0055_meaning,
        reach = R.string.intel_0055_reach,
    ),
    INTEL_0056(
        group = SignalGroup.Attestation,
        meaning = R.string.intel_0056_meaning,
        reach = R.string.intel_0056_reach,
    ),
    INTEL_0057(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0057_meaning,
        reach = R.string.intel_0057_reach,
    ),
    INTEL_0058(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0058_meaning,
        reach = R.string.intel_0058_reach,
    ),
    INTEL_0059(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0059_meaning,
        reach = R.string.intel_0059_reach,
    ),
    INTEL_0060(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0060_meaning,
        reach = R.string.intel_0060_reach,
    ),
    INTEL_0061(
        group = SignalGroup.RuntimeInstrumentation,
        meaning = R.string.intel_0061_meaning,
        reach = R.string.intel_0061_reach,
    ),
    INTEL_0062(
        group = SignalGroup.PackageIntegrity,
        meaning = R.string.intel_0062_meaning,
        reach = R.string.intel_0062_reach,
    ),
    INTEL_0063(
        group = SignalGroup.RootAndSystem,
        meaning = R.string.intel_0063_meaning,
        reach = R.string.intel_0063_reach,
    ),
    ;

    companion object {
        private val byCode = entries.associateBy { it.name }

        /** Null for a code with no row here — registry drift, same as INTEL_UNKNOWN. */
        fun of(code: String): SignalCatalogue? = byCode[code]
    }
}
