#!/usr/bin/env python3
"""Generate the sample app's signal catalogue from the registry + the README catalogue section.

The registry is the source of truth and is append-only, so this is generated
rather than hand-written: a hand-kept copy in the app would drift the moment a
signal is added, and the drift would be invisible (a missing explanation reads
exactly like a signal that has none).

Emits, both fully overwritten each run:
  samples/minimal/src/main/res/values/signals.xml
  samples/minimal/src/main/kotlin/tech/thessemaj/deviceintelligence/sample/signal/SignalCatalogue.kt

  python3 tools/registry/gen-signal-catalogue.py [--check]
"""
import collections
import json
import pathlib
import re
import sys
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "tools/registry/signals-registry.json"
DOCS = ROOT / "README.md"  # the "Signal catalogue" section of the main README
XML_OUT = ROOT / "samples/minimal/src/main/res/values/signals.xml"
KT_OUT = ROOT / "samples/minimal/src/main/kotlin/tech/thessemaj/deviceintelligence/sample/signal/SignalCatalogue.kt"

# The five families the catalogue documents, in docs order. Keyed by the "### "
# heading so a renamed heading fails loudly here rather than silently regrouping.
GROUPS = {
    "Attestation — hardware identity & verified boot": (
        "Attestation", "Attestation",
        "Hardware identity and verified boot: whether the device is what it claims to be.",
    ),
    "Runtime instrumentation — hooks, debuggers, injected code": (
        "RuntimeInstrumentation", "Runtime instrumentation",
        "Hooks, debuggers and injected code: whether this process is being manipulated as it runs.",
    ),
    "Anti-analysis — syscall filtering": (
        "AntiAnalysis", "Anti-analysis",
        "Syscall filtering: whether something is hiding what the process can observe.",
    ),
    "Root & system integrity": (
        "RootAndSystem", "Root and system integrity",
        "Whether the operating system underneath the app is still trustworthy.",
    ),
    "Package integrity — repackaging & tamper": (
        "PackageIntegrity", "Package integrity",
        "Whether the running APK and its DEX are the ones that were signed.",
    ),
    "Virtual environments — emulators & translation": (
        "VirtualEnvironments", "Virtual environments",
        "Whether this device is real silicon or an emulated/translated environment.",
    ),
}


def demarkdown(text):
    """Docs prose carries markdown emphasis and inline code that a TextView shows raw."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def android_escape(text):
    return escape(text).replace("'", "\\'").replace('"', "\\\"")


def parse_docs():
    """code -> (group_key, reach), plus detector -> group_key for undocumented codes."""
    reach, group_of, by_detector = {}, {}, collections.Counter()
    heading = None
    in_catalogue = False
    for line in DOCS.read_text().splitlines():
        if line.startswith("## Signal catalogue"):
            in_catalogue = True
            continue
        if not in_catalogue:
            continue
        if line.startswith("### "):
            heading = line[4:].strip()
            if heading not in GROUPS:
                sys.exit(f"unknown docs section {heading!r} — update GROUPS in {__file__}")
        m = re.match(r"\|\s*`(INTEL_\d+)`\s*\|(.*)\|\s*$", line)
        if m and heading:
            code = m.group(1)
            cells = [c.strip() for c in m.group(2).split("|")]
            reach[code] = demarkdown(cells[-1])
            group_of[code] = heading
    return reach, group_of


def main():
    rows = json.load(REGISTRY.open())["signals"]
    reach, group_of = parse_docs()

    # Codes the docs never listed still need a family; take the one their detector
    # is used for elsewhere. Their reach stays absent rather than invented.
    detector_group = {}
    for r in rows:
        if r["id"] in group_of:
            detector_group.setdefault(r["detector"], collections.Counter())[group_of[r["id"]]] += 1
    fallback = {d: c.most_common(1)[0][0] for d, c in detector_group.items()}

    undocumented = [r["id"] for r in rows
                    if r["id"] not in reach and r.get("status") != "retired"]

    strings = ['<?xml version="1.0" encoding="utf-8"?>',
               "<!-- GENERATED by tools/registry/gen-signal-catalogue.py — do not edit. -->",
               "<!-- TESTBED ONLY (worst-case narrative 2026-09-10, R8): this catalogue bakes the",
               "     FULL detector prose into the app's resources and dex. Fine for this lab app;",
               "     a PRODUCTION app must NOT copy it — that ships the evasion cookbook in",
               "     plaintext to every attacker with apktool. Production renders prose server-side. -->",
               "<resources>"]
    for key, (const, title, blurb) in GROUPS.items():
        strings.append(f'    <string name="signal_group_{const.lower()}">{android_escape(title)}</string>')
        strings.append(f'    <string name="signal_group_{const.lower()}_blurb">{android_escape(blurb)}</string>')
    strings.append("")

    entries = []
    for r in sorted(rows, key=lambda r: r["id"]):
        code = r["id"]
        low = code.lower()
        heading = group_of.get(code) or fallback.get(r["detector"])
        if heading is None:
            sys.exit(f"{code}: no group and no detector fallback")
        const = GROUPS[heading][0]
        retired = r.get("status") == "retired"

        strings.append(f'    <string name="{low}_meaning">{android_escape(r["description"])}</string>')
        reach_ref = "null"
        if code in reach:
            strings.append(f'    <string name="{low}_reach">{android_escape(reach[code])}</string>')
            reach_ref = f"R.string.{low}_reach"

        entries.append(
            f"    {code}(\n"
            f"        group = SignalGroup.{const},\n"
            f"        meaning = R.string.{low}_meaning,\n"
            f"        reach = {reach_ref},\n"
            + (f"        retired = true,\n" if retired else "")
            + f"    ),"
        )
    strings.append("</resources>")

    group_consts = ",\n".join(
        f"    {const}(R.string.signal_group_{const.lower()}, R.string.signal_group_{const.lower()}_blurb)"
        for const, _, _ in GROUPS.values()
    )

    kt = f'''// GENERATED by tools/registry/gen-signal-catalogue.py — do not edit.
//
// TESTBED ONLY (worst-case narrative 2026-09-10, R8): this catalogue and its
// resources bake the FULL detector prose into the app. Fine for this lab app;
// a PRODUCTION app must NOT copy it — that ships the evasion cookbook in
// plaintext to every attacker. Production renders prose server-side.
package tech.thessemaj.deviceintelligence.sample.signal

import androidx.annotation.StringRes
import tech.thessemaj.deviceintelligence.sample.R

/** The families the signal catalogue is organised into. */
enum class SignalGroup(@StringRes val title: Int, @StringRes val blurb: Int) {{
{group_consts},
}}

/**
 * Every signal code the SDK can emit, paired with what it means.
 *
 * The wire carries only the opaque code; `:verifier` resolves the detector, kind,
 * severity and title from the registry. What it does NOT carry is the explanation —
 * the meaning of the finding and the capability it implies — so that lives here,
 * generated from the same registry and the signal catalogue in docs/signals.md.
 *
 * [reach] is null for codes the docs have not described yet.
 */
enum class SignalCatalogue(
    val group: SignalGroup,
    @StringRes val meaning: Int,
    @StringRes val reach: Int?,
    /** A retired code should never arrive. If one does, the registry is out of date. */
    val retired: Boolean = false,
) {{
{chr(10).join(entries)}
    ;

    companion object {{
        private val byCode = entries.associateBy {{ it.name }}

        /** Null for a code with no row here — registry drift, same as INTEL_UNKNOWN. */
        fun of(code: String): SignalCatalogue? = byCode[code]
    }}
}}
'''

    if "--check" in sys.argv:
        stale = [p for p, want in ((XML_OUT, "\n".join(strings) + "\n"), (KT_OUT, kt))
                 if not p.exists() or p.read_text() != want]
        if stale:
            sys.exit("stale generated files: " + ", ".join(str(p) for p in stale))
        print("signal catalogue up to date")
        return

    KT_OUT.parent.mkdir(parents=True, exist_ok=True)
    XML_OUT.write_text("\n".join(strings) + "\n")
    KT_OUT.write_text(kt)
    print(f"wrote {len(rows)} signals across {len(GROUPS)} groups")
    if undocumented:
        print("NOTE: active but absent from docs/signals.md, so no reach text: "
              + ", ".join(undocumented))


main()
