#!/usr/bin/env python3
"""Generate the sample app's signal catalogue and the docs-site catalogue page
from the registry (the single source of truth for codes, meanings and reach).

    python3 tools/registry/gen-signal-catalogue.py           # regenerate
    python3 tools/registry/gen-signal-catalogue.py --check   # fail if stale

Emits, fully overwritten each run:
  samples/minimal/src/main/res/values/signals.xml
  samples/minimal/src/main/kotlin/tech/thessemaj/deviceintelligence/sample/signal/SignalCatalogue.kt
  docs/signal-catalogue.md
"""
import collections
import json
import pathlib
import re
import sys
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "tools/registry/signals-registry.json"
XML_OUT = ROOT / "samples/minimal/src/main/res/values/signals.xml"
KT_OUT = ROOT / "samples/minimal/src/main/kotlin/tech/thessemaj/deviceintelligence/sample/signal/SignalCatalogue.kt"
DOCS_OUT = ROOT / "docs/signal-catalogue.md"

GROUPS = {
    "Attestation — hardware identity & verified boot": (
        "Attestation", "Attestation",
        "Hardware identity and verified boot: whether the device is what it claims to be.",
    ),
    "Runtime instrumentation — hooks, debuggers, injected code": (
        "RuntimeInstrumentation", "Runtime instrumentation",
        "Hooks, debuggers and injected code: whether this process is being manipulated as it runs.",
    ),
    "Anti-analysis — syscall filtering": (
        "AntiAnalysis", "Anti-analysis",
        "Syscall filtering: whether something is hiding what the process can observe.",
    ),
    "Root & system integrity": (
        "RootAndSystem", "Root and system integrity",
        "Whether the operating system underneath the app is still trustworthy.",
    ),
    "Package integrity — repackaging & tamper": (
        "PackageIntegrity", "Package integrity",
        "Whether the running APK and its DEX are the ones that were signed.",
    ),
    "Virtual environments — emulators & translation": (
        "VirtualEnvironments", "Virtual environments",
        "Whether this device is real silicon or an emulated/translated environment.",
    ),
}

DETECTOR_GROUPS = {
    "attestation": "Attestation — hardware identity & verified boot",
    "art": "Runtime instrumentation — hooks, debuggers, injected code",
    "dex": "Runtime instrumentation — hooks, debuggers, injected code",
    "environment": "Runtime instrumentation — hooks, debuggers, injected code",
    "native": "Runtime instrumentation — hooks, debuggers, injected code",
    "native_integrity": "Runtime instrumentation — hooks, debuggers, injected code",
    "self_hook": "Runtime instrumentation — hooks, debuggers, injected code",
    "seccomp": "Anti-analysis — syscall filtering",
    "root": "Root & system integrity",
    "apk": "Package integrity — repackaging & tamper",
    "emulator": "Virtual environments — emulators & translation",
}


def demarkdown(text):
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def android_escape(text):
    return escape(text).replace("'", "\\'").replace('"', '\\"')


def main():
    rows = json.load(REGISTRY.open())["signals"]
    active = [r for r in rows if r.get("status") != "retired"]

    group_of = {}
    for r in rows:
        heading = DETECTOR_GROUPS.get(r["detector"])
        if heading is None:
            sys.exit(f"{r['id']}: detector {r['detector']!r} has no family — update DETECTOR_GROUPS")
        group_of[r["id"]] = heading

    strings = ['<?xml version="1.0" encoding="utf-8"?>',
               "<!-- GENERATED by tools/registry/gen-signal-catalogue.py — do not edit. -->",
               "<!-- TESTBED ONLY (worst-case narrative 2026-09-10, R8): this catalogue bakes the",
               "     FULL detector prose into the app's resources and dex. Fine for this lab app;",
               "     a PRODUCTION app must NOT copy it — that ships the evasion cookbook in",
               "     plaintext to every attacker with apktool. Production renders prose server-side. -->",
               "<resources>"]
    for key, (const, title, blurb) in GROUPS.items():
        strings.append(f'    <string name="signal_group_{const.lower()}">{android_escape(title)}</string>')
        strings.append(f'    <string name="signal_group_{const.lower()}_blurb">{android_escape(blurb)}</string>')
    strings.append("")

    entries = []
    for r in sorted(rows, key=lambda r: r["id"]):
        code = r["id"]
        low = code.lower()
        heading = group_of[code]
        const = GROUPS[heading][0]
        retired = r.get("status") == "retired"
        reach = r.get("reach")

        strings.append(f'    <string name="{low}_meaning">{android_escape(r["description"])}</string>')
        reach_ref = "null"
        if reach:
            strings.append(f'    <string name="{low}_reach">{android_escape(reach)}</string>')
            reach_ref = f"R.string.{low}_reach"

        entries.append(
            f"    {code}(\n"
            f"        group = SignalGroup.{const},\n"
            f"        meaning = R.string.{low}_meaning,\n"
            f"        reach = {reach_ref},\n"
            + ("        retired = true,\n" if retired else "")
            + "    ),"
        )
    strings.append("</resources>")

    group_consts = ",\n".join(
        f"    {const}(R.string.signal_group_{const.lower()}, R.string.signal_group_{const.lower()}_blurb)"
        for const, _, _ in GROUPS.values()
    )

    kt = f"""// GENERATED by tools/registry/gen-signal-catalogue.py — do not edit.
//
// TESTBED ONLY (worst-case narrative 2026-09-10, R8): this catalogue and its
// resources bake the FULL detector prose into the app. Fine for this lab app;
// a PRODUCTION app must NOT copy it — that ships the evasion cookbook in
// plaintext to every attacker. Production renders prose server-side.
package tech.thessemaj.deviceintelligence.sample.signal

import androidx.annotation.StringRes
import tech.thessemaj.deviceintelligence.sample.R

/** The families the signal catalogue is organised into. */
enum class SignalGroup(@StringRes val title: Int, @StringRes val blurb: Int) {{
{group_consts},
}}

/**
 * Every signal code the SDK can emit, paired with what it means.
 *
 * The wire carries only the opaque code; `:verifier` resolves the detector, kind,
 * severity and title from the registry. What it does NOT carry is the explanation —
 * the meaning of the finding and the capability it implies — so that lives here,
 * generated from the same registry.
 *
 * [reach] is null for codes the docs have not described yet.
 */
enum class SignalCatalogue(
    val group: SignalGroup,
    @StringRes val meaning: Int,
    @StringRes val reach: Int?,
    /** A retired code should never arrive. If one does, the registry is out of date. */
    val retired: Boolean = false,
) {{
{chr(10).join(entries)}
    ;

    companion object {{
        private val byCode = entries.associateBy {{ it.name }}

        /** Null for a code with no row here — registry drift, same as INTEL_UNKNOWN. */
        fun of(code: String): SignalCatalogue? = byCode[code]
    }}
}}
"""

    docs = ["# Signal catalogue", "",
            "Every `INTEL_XXXX` code the SDK can emit. The wire carries only the code;",
            "this page is what each one means and what it unlocks for whoever writes",
            "backend policy. Source of truth:",
            "[`tools/registry/signals-registry.json`](https://github.com/iamjosephmj/DeviceIntelligence/blob/main/tools/registry/signals-registry.json).",
            ""]
    undocumented = [r["id"] for r in active if not r.get("reach")]
    for heading, (const, title, blurb) in GROUPS.items():
        docs.append(f"## {heading}")
        docs.append("")
        docs.append(blurb)
        docs.append("")
        docs.append("| Code | detector | kind | Sev | Meaning | Reach — what it unlocks |")
        docs.append("|---|---|---|---|---|---|")
        for r in sorted((r for r in active if group_of[r["id"]] == heading), key=lambda r: r["id"]):
            reach = re.sub(r"\s+", " ", r.get("reach", "")).strip()
            docs.append(f"| `{r['id']}` | {r['detector']} | `{r['kind']}` | {r['severity']} | {r['description']} | {reach} |")
        docs.append("")
    if undocumented:
        docs.append("Codes without reach prose yet: " + ", ".join(f"`{c}`" for c in undocumented) + ".")
        docs.append("")

    if "--check" in sys.argv:
        want = {"\n".join(strings) + "\n": XML_OUT, kt: KT_OUT, "\n".join(docs) + "\n": DOCS_OUT}
        stale = [str(p) for text, p in want.items() if not p.exists() or p.read_text() != text]
        if stale:
            sys.exit("stale generated files: " + ", ".join(stale))
        print("signal catalogue up to date")
        return

    for p, text in ((XML_OUT, "\n".join(strings) + "\n"), (KT_OUT, kt), (DOCS_OUT, "\n".join(docs) + "\n")):
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"wrote {len(rows)} signals across {len(GROUPS)} groups")


main()
