// translation_probe.cpp — runtime.emulator probe for INTEL_0056
// (translated_environment). See translation_classify.h for the classification
// contract; this TU gathers the three inputs and emits the record.
//
// Input hardening, per family convention:
//   - uname(2) via raw syscall (sys::raw_uname): no libc PLT entry to hook.
//     Public emulator-bypass kits hook Build.* fields, __system_property_get
//     and libc fopen/access — none of them intercept the syscall layer, and
//     none rewrite the kernel's own uname answer.
//   - /proc/self/maps via raw openat/read syscalls: same reasoning. The blob
//     is generated by the kernel per read; only a kernel-level (or container
//     namespace) attacker can rewrite it.
//   - ro.dalvik.vm.native.bridge via __system_property_get: hookable, but a
//     spoof only removes the bridge_named sub-fact — divergence and the maps
//     sub-fact are unaffected, and an actual spoof on THIS key is a separate
//     (INTEL_0043-shaped) problem.
// Every read failure contributes nothing. Fail-open; no finding without an
// affirmative sub-fact.

#include "dicore/detectors/emulator/translation/translation_classify.h"
#include "dicore/core/verdict_cores.h"
#include "dicore/platform/syscalls.h"
#include "dicore/platform/obf.h"

#include <fcntl.h>
#include <string>
#include <sys/system_properties.h>
#include <sys/utsname.h>
#include <vector>

namespace dicore {

namespace {

// /proc/self/maps via raw syscalls into an appending string. False on any I/O
// failure -> the maps sub-fact contributes nothing.
bool read_maps_raw(std::string* out) {
    int errno_out = 0;
    int fd = sys::raw_openat(AT_FDCWD, "/proc/self/maps", O_RDONLY, 0, &errno_out);
    if (fd < 0) return false;
    char buf[4096];
    for (;;) {
        ssize_t r = sys::raw_read_full(fd, buf, sizeof(buf), &errno_out);
        if (r < 0) {
            sys::raw_close(fd);
            return false;
        }
        if (r == 0) break;
        out->append(buf, (size_t)r);
        if (out->size() > (1u << 20)) break;   // 1 MiB cap; maps never reaches this
    }
    sys::raw_close(fd);
    return true;
}

const char* process_abi_name() {
#if defined(__aarch64__)
    return "arm64";
#elif defined(__arm__)
    return "arm32";
#elif defined(__x86_64__)
    return "x86_64";
#elif defined(__i386__)
    return "x86";
#else
    return "unknown";
#endif
}

}  // namespace

DI_OBF_EMU
std::vector<std::string> emu_translation_records() {
    constexpr char kFS = '\x1f';
    std::vector<std::string> out;

    // Sub-fact inputs, each fail-open.
    struct utsname un;
    int errno_out = 0;
    if (sys::raw_uname(&un, &errno_out) != 0) return {};
    char bridge[PROP_VALUE_MAX] = {0};
    __system_property_get("ro.dalvik.vm.native.bridge", bridge);
    std::string maps;
    read_maps_raw(&maps);   // failure -> empty blob -> maps sub-fact silent

    emu::TranslationFinding f =
        emu::classify_translation(un.machine, bridge, maps);
    if (!f.affirmative) return {};

    // kind \x1f SEVERITY \x1f k=v|k=v...
    // CRITICAL, not HIGH: the sub-facts are impossible on genuine silicon (the
    // sanctioned-translation exception, ChromeOS/ARC, already trips INTEL_0044 /
    // the pinned-root chain check, so it is no new landing zone), and CRITICAL
    // is what keeps the on_clean_device() string-unlock gate locked on an
    // emulator — on an AVD where the attestation path degrades before the
    // KeyDescription parse, this signal can be the only on-device finding.
    std::string r = "translated_environment";
    r += kFS;
    r += "CRITICAL";
    r += kFS;
    r += "machine=";
    r += f.machine;
    r += "|abi=";
    r += process_abi_name();
    if (f.process_translated) r += "|translated=1";
    if (f.bridge[0] && std::string(f.bridge) != "0") {
        r += "|bridge=";
        r += f.bridge;
    }
    if (f.bridge_mapped) r += "|bridge_mapped=1";
    out.push_back(r);
    return out;
}

}  // namespace dicore
