// anon_exec_probe.cpp — environment probe for INTEL_0057
// (injected_executable_mapping). See anon_exec.hpp for the classification
// contract; this TU reads the maps blob and emits the record.
//
// Maps are read with the SAME raw-syscall reader the maps scan uses
// (maps_scan.cpp → env::read_proc_self_maps): the blob is generated by the
// kernel per read, so no libc PLT entry can serve a doctored copy. Read
// failure contributes nothing — fail-open; only an affirmative finding is
// recorded. Kernel vdso/vvar/vectors/vsyscall/uprobes pages are excluded by
// the classifier, so the findings are mappings no clean loader produces:
// zygisk stub pools (anonymous RWX), Frida gadgets (memfd), unloaded-but-
// mapped payloads ((deleted)).

#include "dicore/core/verdict_cores.h"
#include "dicore/detectors/environment/maps/anon_exec.hpp"
#include "dicore/detectors/environment/maps/maps_parse.h"
#include "dicore/platform/obf.h"

#include <cstdio>
#include <string>
#include <vector>

namespace dicore {

namespace {

// Record detail carries at most this many regions (whole-count still reports;
// the count is the finding, the regions are evidence). Same cap discipline as
// the RWX-region record in maps_scan.cpp.
constexpr size_t kDetailRegions = 8;

}  // namespace

DI_OBF_ORCH
std::vector<std::string> anon_exec_records() {
    constexpr char kFS = '\x1f';
    std::vector<std::string> out;

    std::string maps;
    if (!env::read_proc_self_maps(&maps)) return {};

    // Generously sized: classify returning exactly cap means "possibly more
    // findings", and a process with 128 anon-exec regions is already an
    // attack, not an app — the count (not the tail) is the finding.
    dicore::anon_exec::Finding f[128];
    size_t n = dicore::anon_exec::classify(maps.c_str(), f, 128);
    if (n == 0) return {};

    // kind \x1f SEVERITY \x1f k=v|k=v...
    std::string r = "injected_executable_mapping";
    r += kFS;
    r += "HIGH";
    r += kFS;
    r += "region_count=" + std::to_string(n);
    if (n == 128) r += "|overflow=1";
    for (size_t i = 0; i < n && i < kDetailRegions; ++i) {
        char rb[384];
        std::snprintf(rb, sizeof(rb),
                      "|region_%zu=%llx-%llx %s%s%s",
                      i,
                      (unsigned long long)f[i].start,
                      (unsigned long long)f[i].end,
                      f[i].perms,
                      f[i].memfd ? "memfd " : "",
                      f[i].path[0] ? f[i].path : "[anon]");
        r += rb;
    }
    if (n > kDetailRegions) r += "|more=" + std::to_string(n - kDetailRegions);
    out.push_back(r);
    return out;
}

}  // namespace dicore
